map_num_long: 5
map_num_wide: 5
non_fly_list: []
map_pre_dict: {'(0,0)':['C'], '(0,1)':['C'], '(0,2)': ['C'], '(0,3)':['C'], '(0,4)':['C'], '(1,0)':['C'], '(1,1)':['C'],'(1,2)':['C'], '(1,3)':['C'], '(1,4)':['C'], '(2,0)':['C'], '(2,1)':['C'], '(2,2)':['C'], '(2,3)':['C'], '(2,4)':['C'], '(3,0)':['C'], '(3,1)':['C'], '(3,2)':['C'], '(3,3)':['C'], '(3,4)':['C'], '(4,0)':['C'], '(4,1)':['C'], '(4,2)':['C'], '(4,3)':['C'], '(4,4)':['C']}
