map_num_long: 3
map_num_wide: 3
non_fly_list: ['(1, 1)']
map_pre_dict: {'(0, 1)': ['S', 'N'], '(0, 0)': ['N', 'E'], '(1, 0)': ['W', 'E'], '(1, 1)': [], '(2, 1)': ['S', 'N'], '(1, 2)': ['W', 'E'], '(2, 0)': ['N', 'W'], '(0, 2)': ['S', 'E'], '(2, 2)': ['S', 'W']}
