map_num_long: 3
map_num_wide: 3
non_fly_list: []
map_pre_dict:
  '(0,0)': []
  '(0,1)': ['E']
  '(0,2)': []
  '(1,0)': []
  '(1,1)': ['W','E','N','S']
  '(1,2)': ['S']
  '(2,0)': []
  '(2,1)': ['W']
  '(2,2)': []