map_num_long: 4
map_num_wide: 4
non_fly_list: []
map_pre_dict:
  '(0,0)': []
  '(0,1)': ['E']
  '(0,2)': []
  '(0,3)': []
  '(1,0)': []
  '(1,1)': ['W','E','N','S']
  '(1,2)': ['S']
  '(1,3)': []
  '(2,0)': []
  '(2,1)': ['W']
  '(2,2)': []
  '(2,3)': []
  '(3,0)': []
  '(3,1)': []
  '(3,2)': []
  '(3,3)': []