map_num_long: 5
map_num_wide: 5
non_fly_list: []
map_pre_dict:
  '(0,0)': []
  '(0,1)': []
  '(0,2)': ['C']
  '(0,3)': []
  '(0,4)': []
  '(1,0)': []
  '(1,1)': []
  '(1,2)': []
  '(1,3)': []
  '(1,4)': []
  '(2,0)': []
  '(2,1)': []
  '(2,2)': []
  '(2,3)': []
  '(2,4)': ['C']
  '(3,0)': []
  '(3,1)': []
  '(3,2)': []
  '(3,3)': []
  '(3,4)': []
  '(4,0)': []
  '(4,1)': []
  '(4,2)': ['C']
  '(4,3)': []
  '(4,4)': []