map_num_long: 3
map_num_wide: 3
non_fly_list: ['(0,0)','(0,1)','(2,0)','(2,1)','(0,2)','(2,2)','(1,0)','(1,1)','(1,2)']
map_pre_dict: {'(0,0)': ['N','E'],'(0,1)': ['S','N'],'(2,0)': ['W','N'], '(2,1)': ['S','N'],'(0,2)':['S','E'],'(2,2)':['S','W'], '(1,0)':['E','W'],'(1,1)':[],'(1,2)':['E','W']}

