// Generated by gencpp from file map_maker/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MAP_MAKER_MESSAGE_ADDTWOINTS_H
#define MAP_MAKER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <map_maker/AddTwoIntsRequest.h>
#include <map_maker/AddTwoIntsResponse.h>


namespace map_maker
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace map_maker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_maker::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::map_maker::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::map_maker::AddTwoInts > {
  static const char* value()
  {
    return "map_maker/AddTwoInts";
  }

  static const char* value(const ::map_maker::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::map_maker::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::map_maker::AddTwoInts > 
template<>
struct MD5Sum< ::map_maker::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_maker::AddTwoInts >::value();
  }
  static const char* value(const ::map_maker::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_maker::AddTwoIntsRequest> should match 
// service_traits::DataType< ::map_maker::AddTwoInts > 
template<>
struct DataType< ::map_maker::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::map_maker::AddTwoInts >::value();
  }
  static const char* value(const ::map_maker::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_maker::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::map_maker::AddTwoInts > 
template<>
struct MD5Sum< ::map_maker::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_maker::AddTwoInts >::value();
  }
  static const char* value(const ::map_maker::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_maker::AddTwoIntsResponse> should match 
// service_traits::DataType< ::map_maker::AddTwoInts > 
template<>
struct DataType< ::map_maker::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::map_maker::AddTwoInts >::value();
  }
  static const char* value(const ::map_maker::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MAKER_MESSAGE_ADDTWOINTS_H
