// Generated by gencpp from file map_maker/MapTalkRequest.msg
// DO NOT EDIT!


#ifndef MAP_MAKER_MESSAGE_MAPTALKREQUEST_H
#define MAP_MAKER_MESSAGE_MAPTALKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_maker
{
template <class ContainerAllocator>
struct MapTalkRequest_
{
  typedef MapTalkRequest_<ContainerAllocator> Type;

  MapTalkRequest_()
    {
    }
  MapTalkRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::map_maker::MapTalkRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_maker::MapTalkRequest_<ContainerAllocator> const> ConstPtr;

}; // struct MapTalkRequest_

typedef ::map_maker::MapTalkRequest_<std::allocator<void> > MapTalkRequest;

typedef boost::shared_ptr< ::map_maker::MapTalkRequest > MapTalkRequestPtr;
typedef boost::shared_ptr< ::map_maker::MapTalkRequest const> MapTalkRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_maker::MapTalkRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_maker::MapTalkRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace map_maker

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'map_maker': ['/home/crazyflier/flyingcars/catkin_ws/src/map_maker/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::map_maker::MapTalkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_maker::MapTalkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_maker::MapTalkRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_maker::MapTalkRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_maker::MapTalkRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_maker::MapTalkRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_maker::MapTalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::map_maker::MapTalkRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::map_maker::MapTalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_maker/MapTalkRequest";
  }

  static const char* value(const ::map_maker::MapTalkRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_maker::MapTalkRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::map_maker::MapTalkRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_maker::MapTalkRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct MapTalkRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_maker::MapTalkRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::map_maker::MapTalkRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MAKER_MESSAGE_MAPTALKREQUEST_H
