// Generated by gencpp from file map_maker/MapTalk.msg
// DO NOT EDIT!


#ifndef MAP_MAKER_MESSAGE_MAPTALK_H
#define MAP_MAKER_MESSAGE_MAPTALK_H

#include <ros/service_traits.h>


#include <map_maker/MapTalkRequest.h>
#include <map_maker/MapTalkResponse.h>


namespace map_maker
{

struct MapTalk
{

typedef MapTalkRequest Request;
typedef MapTalkResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapTalk
} // namespace map_maker


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_maker::MapTalk > {
  static const char* value()
  {
    return "6fe7530d7a5e37ff441ff3304b9b549d";
  }

  static const char* value(const ::map_maker::MapTalk&) { return value(); }
};

template<>
struct DataType< ::map_maker::MapTalk > {
  static const char* value()
  {
    return "map_maker/MapTalk";
  }

  static const char* value(const ::map_maker::MapTalk&) { return value(); }
};


// service_traits::MD5Sum< ::map_maker::MapTalkRequest> should match 
// service_traits::MD5Sum< ::map_maker::MapTalk > 
template<>
struct MD5Sum< ::map_maker::MapTalkRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_maker::MapTalk >::value();
  }
  static const char* value(const ::map_maker::MapTalkRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_maker::MapTalkRequest> should match 
// service_traits::DataType< ::map_maker::MapTalk > 
template<>
struct DataType< ::map_maker::MapTalkRequest>
{
  static const char* value()
  {
    return DataType< ::map_maker::MapTalk >::value();
  }
  static const char* value(const ::map_maker::MapTalkRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_maker::MapTalkResponse> should match 
// service_traits::MD5Sum< ::map_maker::MapTalk > 
template<>
struct MD5Sum< ::map_maker::MapTalkResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_maker::MapTalk >::value();
  }
  static const char* value(const ::map_maker::MapTalkResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_maker::MapTalkResponse> should match 
// service_traits::DataType< ::map_maker::MapTalk > 
template<>
struct DataType< ::map_maker::MapTalkResponse>
{
  static const char* value()
  {
    return DataType< ::map_maker::MapTalk >::value();
  }
  static const char* value(const ::map_maker::MapTalkResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MAKER_MESSAGE_MAPTALK_H
